---
- hosts: localhost
  tasks:
    - name: Installs apache web server
      yum: pkg=httpd state=installed update_cache=false
      notify:
        - start httpd

  handlers:
    - name: start httpd
      service: name=httpd state=started
